# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    group_service:
        class: AppBundle\Service\GroupService
        arguments: ['@doctrine.orm.entity_manager']

    user_service:
        class: AppBundle\Service\UserService
        arguments: ['@doctrine.orm.entity_manager', '@group_service']
